# Generated by Django 3.0.7 on 2021-05-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedatos', '0002_auto_20210526_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ot',
            name='id',
        ),
        migrations.AddField(
            model_name='ot',
            name='ALSOT',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
