# Generated by Django 3.0.7 on 2021-05-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedatos', '0003_auto_20210526_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ot',
            name='ALSOT',
        ),
        migrations.AddField(
            model_name='ot',
            name='id',
            field=models.AutoField(auto_created=True, default=6, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
