# Generated by Django 3.0.7 on 2021-05-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedatos', '0004_auto_20210526_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orde_de_Trabajo',
            fields=[
                ('alsot', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=20)),
                ('reporte', models.TextField(max_length=5000)),
                ('accion', models.TextField(max_length=50000)),
                ('tecnico', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OT',
                'verbose_name_plural': "OT's",
            },
        ),
        migrations.RemoveField(
            model_name='ot',
            name='id',
        ),
        migrations.AddField(
            model_name='ot',
            name='alsot',
            field=models.AutoField(default=6, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
