# Generated by Django 3.0.7 on 2021-05-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedatos', '0005_auto_20210526_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orde_de_Trabajo',
        ),
        migrations.RemoveField(
            model_name='ot',
            name='alsot',
        ),
        migrations.AddField(
            model_name='ot',
            name='id',
            field=models.AutoField(auto_created=True, default=6, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
