# Generated by Django 3.0.7 on 2021-05-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedatos', '0006_auto_20210526_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot',
            name='hangar',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ot',
            name='observaciones',
            field=models.TextField(default=6, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ot',
            name='orden',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
    ]
