# Generated by Django 3.0.7 on 2021-05-27 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedatos', '0011_auto_20210526_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.CharField(max_length=50)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedatos.ot')),
            ],
        ),
    ]
